---
title: Syllabus
slug: syllabus
citeproc: true
bibliography: ../../static/bib/references.bib
csl: ../../static/bib/chicago-syllabus-no-bib.csl
output:
  blogdown::html_page:
      toc: TRUE
---

```{r load-libraries, message=FALSE, warning=FALSE, include=FALSE}
library(dplyr)
library(tibble)
library(pander)
```

[^courseinfo]: {-}
  `r blogdown::shortcode("courseinfo")`


## Overview

In modern data analysis, graphics and computational statistics are increasingly used together to explore and identify complex patterns in data and to make and communicate claims under uncertainty. This course will go beyond traditional ideas of charts, graphs, maps (and also statistics!) to equip you with the critical analysis, design and technical skills to analyse and communicate with geographic datasets.

The course emphasises real-world applications. You will work with both new, large-scale behavioural datasets, as well as more traditional, administrative datasets located within various social science domains: Political Science, Crime Science, Urban and Transport Planning. As well as learning how to use graphics and statistics to explore patterns in these data, implementing recent ideas from data journalism you will learn how to communicate research findings – how to tell stories with data.

## Course Objectives


By the end of the course you will

1.	Describe, process and combine geographic datasets from a range of sources
2.	Design statistical graphics that expose structure in geographic data and that are underpinned by established principles in information visualization and cartography
3.	Use modern data science and visualization frameworks to produce coherent data analyses
4.	Apply modern statistical techniques for analysing, representing and communicating data and model uncertainty

## Resources

### Primers

- [@healy_data_2018]\
-- An engaging read that manages to integrate ggplot2 code with key Information Visualization theory and using real social science datasets.\
[Free online (draft version)](https://socviz.co/).


- [@lovelace_geocomputation_2019]\
-- This book comprehensively introduces spatial data handling in R. It is a great complement to R for Data Science in that it draws on brand new libraries that support `tidyverse-style` operations on spatial data.\
[Free online](https://geocompr.robinlovelace.net/).

- [@wickham_r_2017]\
-- _The_ primer for doing data analysis with R. Wickham and Grolemund present a thesis of the data science workflow and illustrates how R and packages that form the `tidyverse` support this. It is both accessible and coherent and is highly recommended.\
[Free online](https://r4ds.had.co.nz/).


### Blogs

- [Flowingdata](http://flowingdata.com) \
-- Nathan Yau, a former statistics PhD from UCLA, has maintained a data vis blog and online training materials for some time. Numerous excellent examples, on the most part implemented in R and `ggplot2`.

- [giCentre](https://www.gicentre.net)  \
-- World-leading group researching and developing geovisualization. Check out recent work on [litvis](https://www.gicentre.net/software#/litvis-1/) and [elm-vega](https://www.gicentre.net/elmvegalite/).

- [Multiple Views](https://medium.com/multiple-views-visualization-research-explained) \
-- Blog series by leading visualization researchers and practitioners.

### Conferences

- [IEEE VIS](http://ieeevis.org/)\
-- *The* conference at which leading Data Visualization work is published through a special issue of [Transactions on Visualization & Computer Graphics](https://ieeexplore.ieee.org/xpl/RecentIssue.jsp?punumber=2945).

- [OpenVis Conf](http://www.openvisconf.com)\
-- New, exciting conference (though last one was in 2018!). Presenters are academics and practitioners. Videos of talks from previous conferences are published online. From the 2018 conference, I'd recommend Matt Kay's on [Uncertainty Visualization](https://www.youtube.com/watch?v=vqzO-9LSoG4&feature=youtu.be), Maarten Lambrechts' [Xenographics](https://www.youtube.com/watch?v=fp-WNqaQG0s&feature=youtu.be) and Heather Krause's [F-Word](https://www.youtube.com/watch?v=uw1Tag08dK4&feature=youtu.be).
