<!DOCTYPE html>
<html lang="en-us" 
      xmlns:og="http://ogp.me/ns#" 
      xmlns:fb="https://www.facebook.com/2008/fbml">

<head>

  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <meta http-equiv="X-UA-Compatible" content="IE=edge">
  <meta name="generator" content="Source Themes Academic 4.8.0">

  

  
  
  
  
  
    
    
    
  
  

  <meta name="author" content="Andrew Heiss">

  
  
  
    
  
  <meta name="description" content="Program details 1. Check balance 2. Estimate difference   There’s no video for this example, since the R code is fairly straightforward, and since I talked about it in the lecture (see the slides).
If you want to follow along with this example, you can download the data below:
  village_randomized.csv  library(tidyverse) # ggplot(), %&gt;%, mutate(), and friends library(ggdag) # Make DAGs library(scales) # Format numbers with functions like comma(), percent(), and dollar() library(broom) # Convert models to data frames library(patchwork) # Combine ggplots into single composite plots set.">

  
  <link rel="alternate" hreflang="en-us" href="https://evalf20.classes.andrewheiss.com/example/rcts/">

  


  
  
  
  <meta name="theme-color" content="#CF4446">
  

  
  
  
  <script src="/js/mathjax-config.js"></script>
  

  
  
  
  
    
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/academicons/1.8.6/css/academicons.min.css" integrity="sha256-uFVgMKfistnJAfoCUQigIl+JfUaP47GrRKjf6CTPVmw=" crossorigin="anonymous">
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/5.12.0-1/css/all.min.css" integrity="sha256-4w9DunooKSr3MFXHXWyFER38WmPdm361bQS/2KUWZbU=" crossorigin="anonymous">
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/fancybox/3.5.7/jquery.fancybox.min.css" integrity="sha256-Vzbj7sDDS/woiFS3uNKo8eIuni59rjyNGtXfstRzStA=" crossorigin="anonymous">

    
    
    
      
    
    
      
      
        
          <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/highlight.js/9.18.1/styles/github.min.css" crossorigin="anonymous" title="hl-light">
          <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/highlight.js/9.18.1/styles/dracula.min.css" crossorigin="anonymous" title="hl-dark" disabled>
        
      
    

    

    

    
    
      

      
      

      
    
      

      
      

      
    
      

      
      

      
    
      

      
      

      
    
      

      
      

      
    
      

      
      

      
    
      

      
      

      
    
      

      
      

      
    
      

      
      

      
    
      

      
      

      
    
      

      
      

      
        <script src="https://cdnjs.cloudflare.com/ajax/libs/lazysizes/5.1.2/lazysizes.min.js" integrity="sha256-Md1qLToewPeKjfAHU1zyPwOutccPAm5tahnaw7Osw0A=" crossorigin="anonymous" async></script>
      
    
      

      
      

      
    
      

      
      

      
    
      

      
      

      
        <script src="https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-chtml.js" integrity="" crossorigin="anonymous" async></script>
      
    
      

      
      

      
    

  

  
  
  
  <link rel="stylesheet" href="https://fonts.googleapis.com/css?family=Fira+Sans+Condensed:400,400i,700,700i%7CNunito+Sans:ital,wght@0,400;0,700;1,400;1,700&display=swap">
  

  
  
  
  
  <link rel="stylesheet" href="/css/academic.css">

  




  


  
  

  

  <link rel="manifest" href="/index.webmanifest">
  <link rel="icon" type="image/png" href="/images/icon_hu0b7a4cb9992c9ac0e91bd28ffd38dd00_9727_32x32_fill_lanczos_center_2.png">
  <link rel="apple-touch-icon" type="image/png" href="/images/icon_hu0b7a4cb9992c9ac0e91bd28ffd38dd00_9727_192x192_fill_lanczos_center_2.png">

  <link rel="canonical" href="https://evalf20.classes.andrewheiss.com/example/rcts/">

  
  
  
  
  
  
  
    
  
  
  <meta property="twitter:card" content="summary_large_image">
  
  <meta property="twitter:site" content="@andrewheiss">
  <meta property="twitter:creator" content="@andrewheiss">
  
  <meta property="og:site_name" content="Program Evaluation">
  <meta property="og:url" content="https://evalf20.classes.andrewheiss.com/example/rcts/">
  <meta property="og:title" content="Randomized controlled trials (RCTs) | Program Evaluation">
  <meta property="og:description" content="Program details 1. Check balance 2. Estimate difference   There’s no video for this example, since the R code is fairly straightforward, and since I talked about it in the lecture (see the slides).
If you want to follow along with this example, you can download the data below:
  village_randomized.csv  library(tidyverse) # ggplot(), %&gt;%, mutate(), and friends library(ggdag) # Make DAGs library(scales) # Format numbers with functions like comma(), percent(), and dollar() library(broom) # Convert models to data frames library(patchwork) # Combine ggplots into single composite plots set."><meta property="og:image" content="https://evalf20.classes.andrewheiss.com/img/social-image-f20.png">
  <meta property="twitter:image" content="https://evalf20.classes.andrewheiss.com/img/social-image-f20.png"><meta property="og:locale" content="en-us">
  
    
      <meta property="article:published_time" content="2020-10-02T00:00:00&#43;00:00">
    
    <meta property="article:modified_time" content="2020-11-28T22:05:44&#43;00:00">
  

  



  


  


    <link rel="stylesheet" type="text/css" href="/custom-css/print.css" media="print" />

    <link rel="shortcut icon" href="https://evalf20.classes.andrewheiss.com/favicon.ico" />
    <link rel="apple-touch-icon-precomposed" sizes="57x57" href="https://evalf20.classes.andrewheiss.com/img/apple-touch-icon-57x57.png" />
    <link rel="apple-touch-icon-precomposed" sizes="114x114" href="https://evalf20.classes.andrewheiss.com/img/apple-touch-icon-114x114.png" />
    <link rel="apple-touch-icon-precomposed" sizes="72x72" href="https://evalf20.classes.andrewheiss.com/img/apple-touch-icon-72x72.png" />
    <link rel="apple-touch-icon-precomposed" sizes="144x144" href="https://evalf20.classes.andrewheiss.com/img/apple-touch-icon-144x144.png" />
    <link rel="apple-touch-icon-precomposed" sizes="120x120" href="https://evalf20.classes.andrewheiss.com/img/apple-touch-icon-120x120.png" />
    <link rel="apple-touch-icon-precomposed" sizes="152x152" href="https://evalf20.classes.andrewheiss.com/img/apple-touch-icon-152x152.png" />
    <link rel="icon" type="image/png" href="https://evalf20.classes.andrewheiss.com/img/favicon-32x32.png" sizes="32x32" />
    <link rel="icon" type="image/png" href="https://evalf20.classes.andrewheiss.com/img/favicon-16x16.png" sizes="16x16" />
    <meta name="application-name" content="PMAP 8521: Program Evaluation" />
    <meta name="msapplication-TileColor" content="#FFFFFF" />
    <meta name="msapplication-TileImage" content="https://evalf20.classes.andrewheiss.com/img/mstile-144x144.png" />


  <title>Randomized controlled trials (RCTs) | Program Evaluation</title>

</head>


<body id="top" data-spy="scroll" data-offset="70"
    data-target="#TableOfContents"
    >

    <aside class="search-results" id="search">
  <div class="container">
    <section class="search-header">

      <div class="row no-gutters justify-content-between mb-3">
        <div class="col-6">
          <h1>Search</h1>
        </div>
        <div class="col-6 col-search-close">
          <a class="js-search" href="#"><i class="fas fa-times-circle text-muted" aria-hidden="true"></i></a>
        </div>
      </div>

      <div id="search-box">
        
        
        
      </div>

    </section>
    <section class="section-search-results">

      <div id="search-hits">
        
      </div>

    </section>
  </div>
</aside>


    







<nav class="navbar navbar-expand-lg navbar-light compensate-for-scrollbar" id="navbar-main">
  <div class="container">

    
    <div class="d-none d-lg-inline-flex">
      <a class="navbar-brand" href="/">Program Evaluation</a>
    </div>
    

    
    <button type="button" class="navbar-toggler" data-toggle="collapse"
            data-target="#navbar-content" aria-controls="navbar" aria-expanded="false" aria-label="Toggle navigation">
    <span><i class="fas fa-bars"></i></span>
    </button>
    

    
    <div class="navbar-brand-mobile-wrapper d-inline-flex d-lg-none">
      <a class="navbar-brand" href="/">Program Evaluation</a>
    </div>
    

    
    
    <div class="navbar-collapse main-menu-item collapse justify-content-end" id="navbar-content">

      
      <ul class="navbar-nav d-md-inline-flex">
        

        

        
        
        
          
        

        
        
        
        
        
        

        <li class="nav-item">
          <a class="nav-link " href="/syllabus/"><span>Syllabus</span></a>
        </li>

        
        

        

        
        
        
          
        

        
        
        
        
        
        

        <li class="nav-item">
          <a class="nav-link " href="/schedule/"><span>Schedule</span></a>
        </li>

        
        

        

        
        
        
          
        

        
        
        
        
        
        

        <li class="nav-item">
          <a class="nav-link " href="/content/"><span>Content</span></a>
        </li>

        
        

        

        
        
        
          
        

        
        
        
        
        
        

        <li class="nav-item">
          <a class="nav-link " href="/assignment/"><span>Assignments</span></a>
        </li>

        
        

        

        
        
        
          
        

        
        
        
        
        
        

        <li class="nav-item">
          <a class="nav-link  active" href="/example/"><span>Examples</span></a>
        </li>

        
        

        

        
        
        
          
        

        
        
        
        
        
        

        <li class="nav-item">
          <a class="nav-link " href="/resource/"><span>Resources</span></a>
        </li>

        
        

        

        
        
        
          
            
          
        

        
        
        
        
        
        

        <li class="nav-item">
          <a class="nav-link " href="https://gsuevalf2020.slack.com" target="_blank" rel="noopener"><span><i class="fab fa-slack"></i></span></a>
        </li>

        
        

        

        
        
        
          
            
          
        

        
        
        
        
        
        

        <li class="nav-item">
          <a class="nav-link " href="https://rstudio.cloud/" target="_blank" rel="noopener"><span>RStudio.cloud</span></a>
        </li>

        
        

      

        
      </ul>
    </div>

    <ul class="nav-icons navbar-nav flex-row ml-auto d-flex pl-md-2">
      

      

      

    </ul>

  </div>
</nav>


    

<div class="container-fluid docs">
    <div class="row flex-xl-nowrap">
        <div class="col-12 col-md-3 col-xl-2 docs-sidebar">
            





  
    
  




<form class="docs-search d-flex align-items-center">
  <button class="btn docs-toggle d-md-none p-0 mr-3" type="button" data-toggle="collapse" data-target="#docs-nav" aria-controls="docs-nav" aria-expanded="false" aria-label="Toggle section navigation">
    <span><i class="fas fa-bars"></i></span>
  </button>

  
</form>

<nav class="collapse docs-links" id="docs-nav">
  

  
  
  
  
  <div class="docs-toc-item">
    <a class="docs-toc-link" href="/example/">Overview</a>
    <ul class="nav docs-sidenav">
      
      <li >
        <a href="/example/">Code examples</a>
      </li>
      
    </ul>
    

  </div>
  
  <div class="docs-toc-item">
    <a class="docs-toc-link" href="/example/random-numbers/">Simulated data</a>
    <ul class="nav docs-sidenav">
      
      <li >
        <a href="/example/random-numbers/">Random numbers</a>
      </li>
      
      <li >
        <a href="/example/synthetic-data/">Synthetic data</a>
      </li>
      
    </ul>
    

  </div>
  
  <div class="docs-toc-item">
    <a class="docs-toc-link" href="/example/rstudio-tidyverse/">Examples</a>
    <ul class="nav docs-sidenav">
      
      <li >
        <a href="/example/rstudio-tidyverse/">R, RStudio, and the tidyverse</a>
      </li>
      
      <li >
        <a href="/example/regression/">Regression</a>
      </li>
      
      <li >
        <a href="/example/dags/">DAGs</a>
      </li>
      
      <li >
        <a href="/example/po-ate-cate/">Potential outcomes, ATEs, and CATEs</a>
      </li>
      
      <li class="active">
        <a href="/example/rcts/">RCTs</a>
      </li>
      
      <li >
        <a href="/example/matching-ipw/">Matching and IPW</a>
      </li>
      
      <li >
        <a href="/example/diff-in-diff/">Diff-in-diff</a>
      </li>
      
      <li >
        <a href="/example/rdd/">Regression discontinuity</a>
      </li>
      
      <li >
        <a href="/example/iv/">Instrumental variables</a>
      </li>
      
      <li >
        <a href="/example/cace/">ITT and CACE</a>
      </li>
      
      <li >
        <a href="/example/rdd-fuzzy/">Fuzzy regression discontinuity</a>
      </li>
      
    </ul>
    

  </div>
  
  
</nav>

        </div>

        

        <main class="col-12 col-md-9 col-xl-8 py-md-3 pl-md-5 docs-content" role="main">

            <article class="article">

                <div class="docs-article-container">
                    <h1>Randomized controlled trials (RCTs)</h1>

                    

                    

                    

                    <div class="article-style">
                        
<script src="/rmarkdown-libs/header-attrs/header-attrs.js"></script>

<div id="TOC">
<ul>
<li><a href="#program-details">Program details</a></li>
<li><a href="#check-balance">1. Check balance</a></li>
<li><a href="#estimate-difference">2. Estimate difference</a></li>
</ul>
</div>

<p>There’s no video for this example, since the R code is fairly straightforward, and since <a href="https://www.youtube.com/watch?v=W0NyALrjLA4&amp;list=PLS6tnpTr39sGJURMOwN9tf9MNDN4t0JMz">I talked about it in the lecture</a> (<a href="/slides/07-slides.html#26">see the slides</a>).</p>
<p>If you want to follow along with this example, you can download the data below:</p>
<ul>
<li><a href="/data/village_randomized.csv"><i class="fas fa-table"></i> <code>village_randomized.csv</code></a></li>
</ul>
<pre class="r"><code>library(tidyverse)  # ggplot(), %&gt;%, mutate(), and friends
library(ggdag)  # Make DAGs
library(scales)  # Format numbers with functions like comma(), percent(), and dollar()
library(broom)  # Convert models to data frames
library(patchwork)  # Combine ggplots into single composite plots

set.seed(1234)   # Make all random draws reproducible</code></pre>
<pre class="r"><code>village_randomized &lt;- read_csv(&quot;data/village_randomized.csv&quot;)</code></pre>
<div id="program-details" class="section level2">
<h2>Program details</h2>
<p>In this hypothetical situation, an NGO is planning on launching a training program designed to boost incomes. Based on their experiences in running pilot programs in other countries, they’ve found that older, richer men tend to self-select into the training program. The NGO’s evaluation consultant (you!) drew this causal model explaining the effect of the program on participant incomes, given the confounding caused by age, sex, and prior income:</p>
<pre class="r"><code>income_dag &lt;- dagify(post_income ~ program + age + sex + pre_income,
                     program ~ age + sex + pre_income,
                     exposure = &quot;program&quot;,
                     outcome = &quot;post_income&quot;,
                     labels = c(post_income = &quot;Post income&quot;,
                                program = &quot;Program&quot;,
                                age = &quot;Age&quot;,
                                sex = &quot;Sex&quot;,
                                pre_income = &quot;Pre income&quot;),
                     coords = list(x = c(program = 1, post_income = 5, age = 2, 
                                         sex = 4, pre_income = 3),
                                   y = c(program = 2, post_income = 2, age = 1, 
                                         sex = 1, pre_income = 3)))

ggdag_status(income_dag, use_labels = &quot;label&quot;, text = FALSE, seed = 1234) + 
  guides(color = FALSE) +
  theme_dag()</code></pre>
<p><img src="/example/rcts_files/figure-html/income-dag-1.png" width="75%" style="display: block; margin: auto;" /></p>
<p>The NGO just received funding to run a randomized controlled trial (RCT) in a village, and you’re excited because you can finally manipulate access to the program—you can calculate <span class="math inline">\(E(\text{Post-income} | do(\text{Program})\)</span>. Following the rules of causal diagrams, you get to delete all the arrows going into the program node:</p>
<pre class="r"><code>income_dag_rct &lt;- dagify(post_income ~ program + age + sex + pre_income,
                         exposure = &quot;program&quot;,
                         outcome = &quot;post_income&quot;,
                         labels = c(post_income = &quot;Post income&quot;,
                                    program = &quot;Program&quot;,
                                    age = &quot;Age&quot;,
                                    sex = &quot;Sex&quot;,
                                    pre_income = &quot;Pre income&quot;),
                         coords = list(x = c(program = 1, post_income = 5, age = 2, 
                                             sex = 4, pre_income = 3),
                                       y = c(program = 2, post_income = 2, age = 1, 
                                             sex = 1, pre_income = 3)))

ggdag_status(income_dag_rct, use_labels = &quot;label&quot;, text = FALSE, seed = 1234) +
  guides(color = FALSE) +
  theme_dag()</code></pre>
<p><img src="/example/rcts_files/figure-html/income-dag-rct-1.png" width="75%" style="display: block; margin: auto;" /></p>
</div>
<div id="check-balance" class="section level2">
<h2>1. Check balance</h2>
<p>You ran the study on 1,000 participants over the course of 6 months and you just got your data back.</p>
<p>Before calculating the effect of the program, you first check to see how well balanced assignment was, and you find that assignment to the program was pretty much split 50/50, which is good:</p>
<pre class="r"><code>village_randomized %&gt;%
  count(program) %&gt;% 
  mutate(prop = n / sum(n))</code></pre>
<pre><code>## # A tibble: 2 x 3
##   program        n  prop
##   &lt;chr&gt;      &lt;int&gt; &lt;dbl&gt;
## 1 No program   503 0.503
## 2 Program      497 0.497</code></pre>
<p>You then check to see how well balanced the treatment and control groups were in participants’ pre-treatment characteristics:</p>
<pre class="r"><code>village_randomized %&gt;% 
  group_by(program) %&gt;% 
  summarize(prop_male = mean(sex_num),
            avg_age = mean(age),
            avg_pre_income = mean(pre_income))</code></pre>
<pre><code>## # A tibble: 2 x 4
##   program    prop_male avg_age avg_pre_income
##   &lt;chr&gt;          &lt;dbl&gt;   &lt;dbl&gt;          &lt;dbl&gt;
## 1 No program     0.584    34.9           803.
## 2 Program        0.604    34.9           801.</code></pre>
<p>These variables appear fairly well balanced. To check that there aren’t any statistically significant differences between the groups, you make some graphs (you could run t-tests too, but graphs are easier for your non-statistical audience to read later).</p>
<p>There were more men in both the treatment and control groups, but the proportion is the same in both, and there’s no substantial difference in sex proportion:</p>
<pre class="r"><code># Here we save each plot as an object so that we can combine the two plots with
# + (which comes from the patchwork package). If you want to see what an
# individual plot looks like, you can run `plot_diff_sex`, or whatever the plot
# object is named.
#
# stat_summary() here is a little different from the geom_*() layers you&#39;ve seen
# in the past. stat_summary() takes a function (here mean_se()) and runs it on
# each of the program groups to get the average and standard error. It then
# plots those with geom_pointrange. The fun.args part of this lets us pass an
# argument to mean_se() so that we can multiply the standard error by 1.96,
# giving us the 95% confidence interval.
plot_diff_sex &lt;- ggplot(village_randomized, aes(x = program, y = sex_num, color = program)) +
  stat_summary(geom = &quot;pointrange&quot;, fun.data = &quot;mean_se&quot;, fun.args = list(mult = 1.96)) +
  guides(color = FALSE) +
  labs(x = NULL, y = &quot;Proportion male&quot;)
# plot_diff_sex  # Uncomment this if you want to see this plot by itself

plot_prop_sex &lt;- ggplot(village_randomized, aes(x = program, fill = sex)) +
  # Using position = &quot;fill&quot; makes the bars range from 0-1 and show the proportion
  geom_bar(position = &quot;fill&quot;) +
  labs(x = NULL, y = &quot;Proportion&quot;, fill = NULL) +
  scale_fill_manual(values = c(&quot;darkblue&quot;, &quot;darkred&quot;))

# Show the plots side-by-side
plot_diff_sex + plot_prop_sex</code></pre>
<p><img src="/example/rcts_files/figure-html/balance-sex-1.png" width="100%" style="display: block; margin: auto;" /></p>
<p>The distribution of ages looks basically the same in the treatment and control groups, and there’s no substantial difference in the average age across groups:</p>
<pre class="r"><code>plot_diff_age &lt;- ggplot(village_randomized, aes(x = program, y = age, color = program)) +
  stat_summary(geom = &quot;pointrange&quot;, fun.data = &quot;mean_se&quot;, fun.args = list(mult = 1.96)) +
  guides(color = FALSE) +
  labs(x = NULL, y = &quot;Age&quot;)

plot_hist_age &lt;- ggplot(village_randomized, aes(x = age, fill = program)) +
  geom_histogram(binwidth = 1, color = &quot;white&quot;) +
  guides(fill = FALSE) +
  labs(x = &quot;Age&quot;, y = &quot;Count&quot;) +
  facet_wrap(vars(program), ncol = 1)

plot_diff_age + plot_hist_age</code></pre>
<p><img src="/example/rcts_files/figure-html/balance-age-1.png" width="100%" style="display: block; margin: auto;" /></p>
<p>Pre-program income is also distributed the same—and has no substantial difference in averages—across treatment and control groups:</p>
<pre class="r"><code>plot_diff_income &lt;- ggplot(village_randomized, aes(x = program, y = pre_income, color = program)) +
  stat_summary(geom = &quot;pointrange&quot;, fun.data = &quot;mean_se&quot;, fun.args = list(mult = 1.96)) +
  guides(color = FALSE) +
  labs(x = NULL, y = &quot;Pre income&quot;)

plot_hist_income &lt;- ggplot(village_randomized, aes(x = pre_income, fill = program)) +
  geom_histogram(binwidth = 20, color = &quot;white&quot;) +
  guides(fill = FALSE) +
  labs(x = &quot;Pre income&quot;, y = &quot;Count&quot;) +
  facet_wrap(vars(program), ncol = 1)

plot_diff_income + plot_hist_income</code></pre>
<p><img src="/example/rcts_files/figure-html/balance-income-1.png" width="100%" style="display: block; margin: auto;" /></p>
<p>All our pre-treatment covariates look good and balanced! You can now estimate the causal effect of the program.</p>
</div>
<div id="estimate-difference" class="section level2">
<h2>2. Estimate difference</h2>
<p>You are interested in the causal effect of the program, or</p>
<p><span class="math display">\[
E[\text{Post income}\ |\ do(\text{Program})]
\]</span></p>
<p>You can find this causal effect by calculating the average treatment effect:</p>
<p><span class="math display">\[
\text{ATE} = E(\overline{\text{Post income }} | \text{ Program} = 1) - E(\overline{\text{Post income }} | \text{ Program} = 0)
\]</span></p>
<p>This is simply the average outcome for people in the program minus the average outcome for people not in the program. You calculate the group averages:</p>
<pre class="r"><code>village_randomized %&gt;% 
  group_by(program) %&gt;% 
  summarize(avg_post = mean(post_income))</code></pre>
<pre><code>## # A tibble: 2 x 2
##   program    avg_post
##   &lt;chr&gt;         &lt;dbl&gt;
## 1 No program    1180.
## 2 Program       1279.</code></pre>
<p>That’s 1279 − 1180, or 99, which means that the program caused an increase of $99 in incomes, on average.</p>
<p>Finding that difference required some manual math, so as a shortcut, you run a regression model with post-program income as the outcome variable and the program indicator variable as the explanatory variable. The coefficient for <code>program</code> is the causal effect (and it includes information about standard errors and significance). You find the same result:</p>
<pre class="r"><code>model_rct &lt;- lm(post_income ~ program, data = village_randomized)
tidy(model_rct)</code></pre>
<pre><code>## # A tibble: 2 x 5
##   term           estimate std.error statistic  p.value
##   &lt;chr&gt;             &lt;dbl&gt;     &lt;dbl&gt;     &lt;dbl&gt;    &lt;dbl&gt;
## 1 (Intercept)      1180.       4.27     276.  0.      
## 2 programProgram     99.2      6.06      16.4 1.23e-53</code></pre>
<p>Based on your RCT, you conclude that the program causes an average increase of $99.25 in income.</p>
<pre class="r"><code>ggplot(village_randomized, aes(x = program, y = post_income, color = program)) +
  stat_summary(geom = &quot;pointrange&quot;, fun.data = &quot;mean_se&quot;, fun.args = list(mult = 1.96)) +
  guides(color = FALSE) +
  labs(x = NULL, y = &quot;Post income&quot;)</code></pre>
<p><img src="/example/rcts_files/figure-html/rct-finding-1.png" width="75%" style="display: block; margin: auto;" /></p>
</div>

                    </div>

                    



                    
                </div>

                <div class="body-footer">
                    <p>Last updated on November 28, 2020</p>

                    





  
  

<p class="edit-page">
  <a href="https://github.com/andrewheiss/evalf20.classes.andrewheiss.com/edit/master/content/example/rcts.html">
    <i class="fas fa-pen pr-2"></i>Edit this page
  </a>
</p>




                    

                </div>

            </article>

            <footer>
    <hr>

    <div class="row course-info">
        <div class="col-md-7">
            <p>
                <strong>PMAP 8521: Program Evaluation (Fall 2020)</strong><br>

                <a href="https://www.gsu.edu" target="_blank" rel="noopener">Georgia State University</a> &emsp;&emsp;
                <a href="https://aysps.gsu.edu/" target="_blank" rel="noopener">Andrew Young School of Policy Studies</a>
            </p>

            <p>
                <a href="https://www.andrewheiss.com" target="_blank" rel="noopener"><i class="fas fa-user"></i>
                    Dr. Andrew Heiss</a> &emsp;&emsp;
                <a href="mailto:aheiss@gsu.edu"><i class="fas fa-envelope"></i>
                    aheiss@gsu.edu</a>
            </p>

            <p>
                <i class="far fa-calendar-alt"></i> Any day &emsp;&emsp;
                <i class="far fa-clock"></i> Any time 
                
            </p>
        </div>

        <div class="col-md-5 credits">
            <p>All content licensed under a <a href="https://creativecommons.org/licenses/by-nc-nd/4.0/" target="_blank" rel="noopener">Creative Commons Attribution-NonCommercial-NoDerivatives 4.0 International License</a>.</p>
            
            <p>Content <i class="fab fa-creative-commons"></i> 2020 <a href="https://www.andrewheiss.com" target="_blank" rel="noopener">Andrew Heiss</a></p>
        
            <p>This site created with the <a href="https://sourcethemes.com/academic/" target="_blank" rel="noopener">Academic theme</a> in <a href="https://bookdown.org/yihui/blogdown/" target="_blank" rel="noopener">blogdown</a> and <a href="https://gohugo.io/" target="_blank" rel="noopener">Hugo</a>. </p>
            
            <p><a href="https://github.com/andrewheiss/evalf20.classes.andrewheiss.com" target="_blank" rel="noopener"><i class="fab fa-github"></i> View the source at GitHub.</a></p>
        </div>
    </div>
</footer>


        </main>
    </div>
</div>

        

    
    
    
      <script src="https://cdnjs.cloudflare.com/ajax/libs/jquery/3.4.1/jquery.min.js" integrity="sha256-CSXorXvZcTkaix6Yvo6HppcZGetbYMGWSFlBw8HfCJo=" crossorigin="anonymous"></script>
      <script src="https://cdnjs.cloudflare.com/ajax/libs/jquery.imagesloaded/4.1.4/imagesloaded.pkgd.min.js" integrity="sha256-lqvxZrPLtfffUl2G/e7szqSvPBILGbwmsGE1MKlOi0Q=" crossorigin="anonymous"></script>
      <script src="https://cdnjs.cloudflare.com/ajax/libs/jquery.isotope/3.0.6/isotope.pkgd.min.js" integrity="sha256-CBrpuqrMhXwcLLUd5tvQ4euBHCdh7wGlDfNz8vbu/iI=" crossorigin="anonymous"></script>
      <script src="https://cdnjs.cloudflare.com/ajax/libs/fancybox/3.5.7/jquery.fancybox.min.js" integrity="sha256-yt2kYMy0w8AbtF89WXb2P1rfjcP/HTHLT7097U8Y5b8=" crossorigin="anonymous"></script>

      

      
        
        <script src="https://cdnjs.cloudflare.com/ajax/libs/highlight.js/9.18.1/highlight.min.js" integrity="sha256-eOgo0OtLL4cdq7RdwRUiGKLX9XsIJ7nGhWEKbohmVAQ=" crossorigin="anonymous"></script>
        
        <script src="https://cdnjs.cloudflare.com/ajax/libs/highlight.js/9.18.1/languages/r.min.js"></script>
        
      

    

    
    

    
    
    <script>const code_highlighting = true;</script>
    

    
    
    <script>const isSiteThemeDark = false;</script>
    

    

    
    
    <script src="https://cdnjs.cloudflare.com/ajax/libs/anchor-js/4.1.1/anchor.min.js" integrity="sha256-pB/deHc9CGfFpJRjC43imB29Rse8tak+5eXqntO94ck=" crossorigin="anonymous"></script>
    <script>
      anchors.add();
    </script>
    

    

    
    

    
    

    
    

    
    

    
    
    
    
    
    
    
    
    
    
    
    
    <script src="/js/academic.min.6f7ce8be710290b8c431bbc97f405d15.js"></script>

    



    
    

    
<div id="modal" class="modal fade" role="dialog">
  <div class="modal-dialog">
    <div class="modal-content">
      <div class="modal-header">
        <h5 class="modal-title">Cite</h5>
        <button type="button" class="close" data-dismiss="modal" aria-label="Close">
          <span aria-hidden="true">&times;</span>
        </button>
      </div>
      <div class="modal-body">
        <pre><code class="tex hljs"></code></pre>
      </div>
      <div class="modal-footer">
        <a class="btn btn-outline-primary my-1 js-copy-cite" href="#" target="_blank">
          <i class="fas fa-copy"></i> Copy
        </a>
        <a class="btn btn-outline-primary my-1 js-download-cite" href="#" target="_blank">
          <i class="fas fa-download"></i> Download
        </a>
        <div id="modal-error"></div>
      </div>
    </div>
  </div>
</div>

</body>

</html>
