---
title: "Visualization for model building 1: Expose, estimate, evaluate"
linktitle: "6: Visualization for model building 1"
date: "2021-06-15"
class_date: "2021-06-15"
citeproc: false
bibliography: ../../static/bib/references.bib
csl: ../../static/bib/chicago-syllabus-no-bib.csl
output:
  blogdown::html_page:
    template: ../../pandoc/toc-title_html.template
    toc: true
menu:
  class:
    parent: Class
    weight: 1
type: docs
weight: 1
editor_options:
  chunk_output_type: console
---

Brexit analysis : https://github.com/ropensci/nomisr
Trump analysis : https://walker-data.com/tidycensus/

Quote from Spiegelhalter? About explanation of variation in context of what remains unexplained

* Models as functions
* Vocabulary: outcome variable (whose variation you are trying to understand), explanatory (other variables that you want to use to explain variation), predicted value (output o the model function -- expected outcome conditioing on explanatory variables), residuals (a measure of how far each case is from the predicted value)

Why models and not graphics
* Can reveal patterns that not evident in graphics -- in regression framework we can *condition* on explanatory variables and talk about the effect of single variables net of others.
* Deal with uncertainty and false discovery -- we infer/overinterpet from scatterplots


Use tidymodels : https://cfss.uchicago.edu/notes/start-with-models/
