---
title: "Visualization for communication and storytelling"
linktitle: "9: Visualization for communication and storytelling"
date: "2021-06-29"
class_date: "2021-07-19"
citeproc: false
bibliography: ../../static/bib/references.bib
csl: ../../static/bib/chicago-syllabus-no-bib.csl
output:
  blogdown::html_page:
    template: ../../pandoc/toc-title_html.template
    toc: true
# menu:
#   class:
#     parent: Class
#     weight: 1
type: docs
weight: 1
editor_options:
  chunk_output_type: console
---


```{r setup, echo=FALSE, eval=TRUE, message=FALSE, warning=FALSE}
library(knitr)
library(kableExtra)
library(tidyverse)
library(here)
```

## Concepts


## Introduction

1. Statistical literacy, scientific communication and data journalism --> evidence-based society. data is now embedded in most domains, and particularly in the public sphere.
2. Covid-19 excellent example. Never before has ...
3. Responsibility in constructing evidence-based arguments, with authority and uncertainty. Point at tensions -- need to reduce complexity (and uncertainty) can lead to false interpretation.
4. That in academic visualization there has been a realisation of the role of storytelling in visualization. Not a single, optimum solution to any visualization problem that expose the true picture/story -- no such formulation exists.
5. This session looks at approaches to communicating case data in Covid-19 data -- recommendations.

Art of statistics on communication?


{{% alert instruction %}}
Themes -- theoretical and cognitive optimal ways of displaying data. No canonical solution exists. And the objectives/purposes are different when communicating. Log-scales (focus on comparison).
Watch Jon Burn-Murdoch's talk at IEEE VIS 2020 on lessons learned around generating (visual) data stories around the Covid-19 pandemic skip to 15:15 to 45:00.

{{% /alert %}}

<div class="embed-responsive embed-responsive-16by9">
<iframe class="embed-responsive-item" src="https://www.youtube.com/embed/xlN_QUdT6os" frameborder="0" allow="accelerometer; autoplay; encrypted-media; gyroscope; picture-in-picture" allowfullscreen></iframe>
</div>

## Concepts

### Data-driven storytelling

*We think this movement towards data-driven stories, which is apparent in both the data visualization research community and the professional journalism community, has the potential to form a crucial part of keeping the public informed, a movement sometimes referred to as the democratization of data – the making of data understandable to the general public. This exciting new development in the use of data visualization in media has revealed an emerging professional community in the already complex group of disciplines involved in data visualization. Data visualization has roots in many research fields including perception, computer graphics, design, and human-computer interaction, though only recently has this expanded to include journalism.

Data journalism
here has also been a growing consciousness that some of today’s most relevant stories are buried in data. This data can be quite hard to understand in its raw formats but can become much more generally accessible when visualized. Journalists have not only begun to use standard data visualizations such as charts and maps in their stories, but are also creating new ones that are tailored to the particular data type and to the message of the story they are writing. Since journalists are now able to easily share interactive data visualizations on the Web, the democratization of data visualization is accelerating with new compelling data visualizations emerging in the media daily...

By carefully structuring the information and integrating explanation to guide the consumer, journalists help lead readers towards a valid interpretation of the underlying data.


Characteristics of visual stoty telling (Roth):

* **designed** : deliberate process -- an intended purpose, with the designer making intentional decisions about composition to develop the broader lesson or moral In this way, the goal of visual storytelling is not just to ‘show’ but also to ‘explain’
* **partial** : prioritize essential information needed to follow the narrative, often emphasizing a small set of key characters, places, and events while ignoring others. Visual stories privilege brevity over completeness
* **intuitive** : at visual stories are partial abstractions generally makes them easier to understand due to reduced information complexity. However, visual storytelling also closely reflects the human experience of place-based events, serving as a congruent metaphor to improve communication  visual storytelling operationalizes these abilities, establishing a clear entry point to start the story and clean transitions between scenes to mark unambiguous story progression (Segel and Heer, 2010).
* **compelling** : Visual stories often capture our attention through a vivid array of graphics, images, and other multimedia, that, when combined with maps, develop a richer sense of place than vector linework alone
* **Relatable** : promote empathy; the audience puts themselves into the story setting, assumes the roles of the characters, and draws from personal experience to add context (Gershon and Page, 2001). In this way, visual storytelling humanizes maps, ‘bringing to life’ the real people imperfectly captured by the data (Caquard et al., 2009: 90). Visual storytelling often is described as more appealing approach to cartography and visualization, but these feelings need not be pleasant if the story deserves a somber, irritated, or even enraged mood. Story and narrative are central to cartographic research on affect and emotion (e.g., Kwan, 2007; Kwan and Ding, 2008; Nold, 2009; Roberts, 2014), with visual stories designed both to represent the emotions of people in the story and evoke emotions from the audience (Griffin and McQuoid, 2012). Accordingly, visual stories perhaps should be judged less on how efficiently or effectively they are read or understood, but instead how they make the audience feel about and connect to other people and places.
* **Memorable** :
* ** Situated** : Visual stories present meaning from a grounded perspective (Pearce, 2014), from ‘somewhere’ and ‘someone’ in contrast to the objective view from ‘nowhere’ and ‘no one’ often assumed in cartography and related design fields
* **Persuasive**
* ** Political** ]
* ** Fluid**

Roth Storytelling : https://www.tandfonline.com/doi/full/10.1080/00087041.2019.1633103?src=recsys

https://blog.datawrapper.de/coronaviruscharts/

Not sure about this resource : https://datajournalism.com/read/handbook/one/delivering-data/using-visualizations-to-tell-stories



Practical : avoid legends, make labels intrinsic to vis. Sacrifice data density? Build sequentially towards complexity. Design consistency.


### Financial Times "Death Chart"

Decisions :

1. Start at days elapsed since first *n* cases to allow comparison between where things are at that pint in the pandemic
2. Log scale -- how quickly cases are doubling -- supports/simplifies visual judgements
3. Annotated with important events -- judgements about effect of events


### Visual salience

Affects how information is perceived. Whereas in a table one scans down the rows and columns, in a visualization one acquires information according to what is most visually salient. Therefore we can think about there being a visual saliency hierarchy that we need to exploit.

* using encodings exploit our cognitive abilities (obviously)
* use layout to encourage comparison (obviously)
* emphasise important and de-emphasise unimportant (needs more subjective decision making -- less obvious)

### Match symbolisation to purpose

### Intuitive

Guide from the familiar to the unfamiliar > animation > Twitter stories (for data vis) : anything on this? examples? Animated rescaling : https://twitter.com/jwoLondon/status/1347208824495726592

Connected scatterplot and scrollable story : https://flourish.studio/2021/04/06/masters-connected-scatter-maarten-lambrechts/
twitter narrative : https://twitter.com/maartenzam/status/1319622943526293505

### Partial

Reduce visual judgement to deviation from thing we are interested in
https://www.hippocraticpost.com/covid-19-update/how-to-tell-if-were-beating-covid-19/
https://aatishb.com/covidtrends/
Plotting growth rate against cumulative cases
Excellent definition of log scales
Plot new cases
Don't plot time! -- total numbers (x) and growth rate (new cases in last week)

Excess deaths charts
Thresholds --- https://twitter.com/romsson/status/1249429612737724419

### Graphical integrity

https://www.statschat.org.nz/wp-content/uploads/2020/04/fox-axis.jpeg

* lie factor = size of effect shown in graphic / size of effect in the data

https://datajournalism.com/read/handbook/one/delivering-data/using-visualizations-to-tell-stories

## Techniques

US Covid-19 dataset (covdata)



<!-- Concerns around the _reproducibility crisis_ are not simply a function of transparency in methodology and research design. Rather, they relate to a culture and incentive structure whereby scientific claims are conferred with authority when reported within the (slightly backwards) logic of Null Hypothesis Significance Testing (NHST) and _p-values_. We will cover a little on this in session 7 and 8, but for an accessible read on the phenomenon of _p-hacking_ (with interactive graphic) see [this article](https://fivethirtyeight.com/features/science-isnt-broken/#part1) from the excellent [FiveThirtyEight](http://fivethirtyeight.com) website. Again, the upshot of all this introspection is a rethinking of the way in which Statistics is taught in schools and universities, with greater emphasis on understanding through computational approaches rather than traditional equations, formulas and probability tables. Where does `R` fit within this? Simply put: `R` is far better placed than traditional software tools and point-and-click paradigms for supporting computational approaches to statistics -- with a set of methods and libraries for performing simulations and permutation-based tests. -->
